// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents Byte Data item.
public struct ByteDataItem: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The type of byte data
  public var byteDataType: ByteDataItem.ByteItemType = ByteDataItem.ByteItemType()

  /// Required. Bytes Data
  public var byteData: Foundation.Data = Foundation.Data()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ByteDataItem`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ByteDataItem().with { $0.byteDataType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let byteDataType = CodingKeys(stringValue: "byteDataType")
    static let byteData = CodingKeys(stringValue: "byteData")

    static let _knownKeys: Set<Swift.String> = [
      "byteDataType",
      "byteData",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      ByteDataItem.ByteItemType.self, forKey: .byteDataType)
    {
      self.byteDataType = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .byteData) {
      self.byteData = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.byteDataType, forKey: .byteDataType)
    try container.encode(self.byteData, forKey: .byteData)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Option to specify the type of byte data.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ByteItemType: Codable, Equatable, Sendable {
    /// Unused
    case unspecified
    /// plain text
    case plaintextUtf8
    /// PDF
    case pdf
    /// DOCX, DOCM, DOTX, DOTM
    case wordDocument
    /// XLSX, XLSM, XLTX, XLYM
    case excelDocument
    /// PPTX, PPTM, POTX, POTM, POT
    case powerpointDocument
    /// TXT
    case txt
    /// CSV
    case csv
    /// IMAGE
    case image
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .plaintextUtf8: return 1
      case .pdf: return 2
      case .wordDocument: return 3
      case .excelDocument: return 4
      case .powerpointDocument: return 5
      case .txt: return 6
      case .csv: return 7
      case .image: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BYTE_ITEM_TYPE_UNSPECIFIED"
      case .plaintextUtf8: return "PLAINTEXT_UTF8"
      case .pdf: return "PDF"
      case .wordDocument: return "WORD_DOCUMENT"
      case .excelDocument: return "EXCEL_DOCUMENT"
      case .powerpointDocument: return "POWERPOINT_DOCUMENT"
      case .txt: return "TXT"
      case .csv: return "CSV"
      case .image: return "IMAGE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ByteItemType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BYTE_ITEM_TYPE_UNSPECIFIED": self = .unspecified
      case "PLAINTEXT_UTF8": self = .plaintextUtf8
      case "PDF": self = .pdf
      case "WORD_DOCUMENT": self = .wordDocument
      case "EXCEL_DOCUMENT": self = .excelDocument
      case "POWERPOINT_DOCUMENT": self = .powerpointDocument
      case "TXT": self = .txt
      case "CSV": self = .csv
      case "IMAGE": self = .image
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ByteItemType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .plaintextUtf8
      case 2: self = .pdf
      case 3: self = .wordDocument
      case 4: self = .excelDocument
      case 5: self = .powerpointDocument
      case 6: self = .txt
      case 7: self = .csv
      case 8: self = .image
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("BYTE_ITEM_TYPE_UNSPECIFIED")
      case .plaintextUtf8: return try container.encode("PLAINTEXT_UTF8")
      case .pdf: return try container.encode("PDF")
      case .wordDocument: return try container.encode("WORD_DOCUMENT")
      case .excelDocument: return try container.encode("EXCEL_DOCUMENT")
      case .powerpointDocument: return try container.encode("POWERPOINT_DOCUMENT")
      case .txt: return try container.encode("TXT")
      case .csv: return try container.encode("CSV")
      case .image: return try container.encode("IMAGE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.ByteDataItem"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
