// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents Data item
public struct DataItem: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Either of text or bytes data.
  public var dataItem: OneOf_DataItem? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataItem`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataItem().with { $0.text = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let text = CodingKeys(stringValue: "text")
    static let byteItem = CodingKeys(stringValue: "byteItem")

    static let _knownKeys: Set<Swift.String> = [
      "text",
      "byteItem",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var dataItem: OneOf_DataItem? = nil
    let dataItemCheckAndSet = {
      if dataItem != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataItem'"))
      }
      dataItem = $0
    }
    if let text = try container.decodeIfPresent(Swift.String.self, forKey: .text) {
      try dataItemCheckAndSet(.text(text))
    }
    if let byteItem = try container.decodeIfPresent(ByteDataItem?.self, forKey: .byteItem) {
      try dataItemCheckAndSet(.byteItem(byteItem))
    }
    self.dataItem = dataItem
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.dataItem {
      switch choice {
      case .text(let value):
        try container.encode(value, forKey: .text)
      case .byteItem(let value):
        try container.encode(value, forKey: .byteItem)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Either of text or bytes data.
  public enum OneOf_DataItem: Codable, Equatable, Sendable {
    /// Plaintext string data for sanitization.
    case text(Swift.String)
    /// Data provided in the form of bytes.
    indirect case byteItem(ByteDataItem?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.DataItem"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
