// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Filter Result obtained after Sanitization operations.
public struct FilterResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Encapsulates one of responsible AI, Sensitive Data Protection, Prompt
  /// Injection and Jailbreak, Malicious URI, CSAM, Virus Scan related filter
  /// results.
  public var filterResult: FilterResultOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FilterResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FilterResult().with { $0.raiFilterResult = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let raiFilterResult = CodingKeys(stringValue: "raiFilterResult")
    static let sdpFilterResult = CodingKeys(stringValue: "sdpFilterResult")
    static let piAndJailbreakFilterResult = CodingKeys(stringValue: "piAndJailbreakFilterResult")
    static let maliciousUriFilterResult = CodingKeys(stringValue: "maliciousUriFilterResult")
    static let csamFilterFilterResult = CodingKeys(stringValue: "csamFilterFilterResult")
    static let virusScanFilterResult = CodingKeys(stringValue: "virusScanFilterResult")

    static let _knownKeys: Set<Swift.String> = [
      "raiFilterResult",
      "sdpFilterResult",
      "piAndJailbreakFilterResult",
      "maliciousUriFilterResult",
      "csamFilterFilterResult",
      "virusScanFilterResult",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var filterResult: FilterResultOneOf? = nil
    let filterResultCheckAndSet = {
      if filterResult != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'filterResult'"))
      }
      filterResult = $0
    }
    if let raiFilterResult = try container.decodeIfPresent(
      RaiFilterResult?.self, forKey: .raiFilterResult)
    {
      try filterResultCheckAndSet(.raiFilterResult(raiFilterResult))
    }
    if let sdpFilterResult = try container.decodeIfPresent(
      SdpFilterResult?.self, forKey: .sdpFilterResult)
    {
      try filterResultCheckAndSet(.sdpFilterResult(sdpFilterResult))
    }
    if let piAndJailbreakFilterResult = try container.decodeIfPresent(
      PiAndJailbreakFilterResult?.self, forKey: .piAndJailbreakFilterResult)
    {
      try filterResultCheckAndSet(.piAndJailbreakFilterResult(piAndJailbreakFilterResult))
    }
    if let maliciousUriFilterResult = try container.decodeIfPresent(
      MaliciousUriFilterResult?.self, forKey: .maliciousUriFilterResult)
    {
      try filterResultCheckAndSet(.maliciousUriFilterResult(maliciousUriFilterResult))
    }
    if let csamFilterFilterResult = try container.decodeIfPresent(
      CsamFilterResult?.self, forKey: .csamFilterFilterResult)
    {
      try filterResultCheckAndSet(.csamFilterFilterResult(csamFilterFilterResult))
    }
    if let virusScanFilterResult = try container.decodeIfPresent(
      VirusScanFilterResult?.self, forKey: .virusScanFilterResult)
    {
      try filterResultCheckAndSet(.virusScanFilterResult(virusScanFilterResult))
    }
    self.filterResult = filterResult
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.filterResult {
      switch choice {
      case .raiFilterResult(let value):
        try container.encode(value, forKey: .raiFilterResult)
      case .sdpFilterResult(let value):
        try container.encode(value, forKey: .sdpFilterResult)
      case .piAndJailbreakFilterResult(let value):
        try container.encode(value, forKey: .piAndJailbreakFilterResult)
      case .maliciousUriFilterResult(let value):
        try container.encode(value, forKey: .maliciousUriFilterResult)
      case .csamFilterFilterResult(let value):
        try container.encode(value, forKey: .csamFilterFilterResult)
      case .virusScanFilterResult(let value):
        try container.encode(value, forKey: .virusScanFilterResult)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Encapsulates one of responsible AI, Sensitive Data Protection, Prompt
  /// Injection and Jailbreak, Malicious URI, CSAM, Virus Scan related filter
  /// results.
  public enum FilterResultOneOf: Codable, Equatable, Sendable {
    /// Responsible AI filter results.
    indirect case raiFilterResult(RaiFilterResult?)
    /// Sensitive Data Protection results.
    indirect case sdpFilterResult(SdpFilterResult?)
    /// Prompt injection and Jailbreak filter results.
    indirect case piAndJailbreakFilterResult(PiAndJailbreakFilterResult?)
    /// Malicious URI filter results.
    indirect case maliciousUriFilterResult(MaliciousUriFilterResult?)
    /// CSAM filter results.
    indirect case csamFilterFilterResult(CsamFilterResult?)
    /// Virus scan results.
    indirect case virusScanFilterResult(VirusScanFilterResult?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.FilterResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
