// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Filters configuration.
public struct FilterConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Responsible AI settings.
  public var raiSettings: RaiFilterSettings? = nil

  /// Optional. Sensitive Data Protection settings.
  public var sdpSettings: SdpFilterSettings? = nil

  /// Optional. Prompt injection and Jailbreak filter settings.
  public var piAndJailbreakFilterSettings: PiAndJailbreakFilterSettings? = nil

  /// Optional. Malicious URI filter settings.
  public var maliciousUriFilterSettings: MaliciousUriFilterSettings? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FilterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FilterConfig().with { $0.raiSettings = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let raiSettings = CodingKeys(stringValue: "raiSettings")
    static let sdpSettings = CodingKeys(stringValue: "sdpSettings")
    static let piAndJailbreakFilterSettings = CodingKeys(
      stringValue: "piAndJailbreakFilterSettings")
    static let maliciousUriFilterSettings = CodingKeys(stringValue: "maliciousUriFilterSettings")

    static let _knownKeys: Set<Swift.String> = [
      "raiSettings",
      "sdpSettings",
      "piAndJailbreakFilterSettings",
      "maliciousUriFilterSettings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.raiSettings = try container.decodeIfPresent(RaiFilterSettings.self, forKey: .raiSettings)
    self.sdpSettings = try container.decodeIfPresent(SdpFilterSettings.self, forKey: .sdpSettings)
    self.piAndJailbreakFilterSettings = try container.decodeIfPresent(
      PiAndJailbreakFilterSettings.self, forKey: .piAndJailbreakFilterSettings)
    self.maliciousUriFilterSettings = try container.decodeIfPresent(
      MaliciousUriFilterSettings.self, forKey: .maliciousUriFilterSettings)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.raiSettings, forKey: .raiSettings)
    try container.encodeIfPresent(self.sdpSettings, forKey: .sdpSettings)
    try container.encodeIfPresent(
      self.piAndJailbreakFilterSettings, forKey: .piAndJailbreakFilterSettings)
    try container.encodeIfPresent(
      self.maliciousUriFilterSettings, forKey: .maliciousUriFilterSettings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.FilterConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
