// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing FloorSetting resource
public struct FloorSetting: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name.
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create timestamp
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. [Output only] Update timestamp
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Required. ModelArmor filter configuration.
  public var filterConfig: FilterConfig? = nil

  /// Optional. Floor Settings enforcement status.
  public var enableFloorSettingEnforcement: Swift.Bool? = nil

  /// Optional. List of integrated services for which the floor setting is
  /// applicable.
  public var integratedServices: [FloorSetting.IntegratedService] = []

  /// Optional. AI Platform floor setting.
  public var aiPlatformFloorSetting: AiPlatformFloorSetting? = nil

  /// Optional. Metadata for FloorSetting
  public var floorSettingMetadata: FloorSetting.FloorSettingMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FloorSetting`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FloorSetting().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let filterConfig = CodingKeys(stringValue: "filterConfig")
    static let enableFloorSettingEnforcement = CodingKeys(
      stringValue: "enableFloorSettingEnforcement")
    static let integratedServices = CodingKeys(stringValue: "integratedServices")
    static let aiPlatformFloorSetting = CodingKeys(stringValue: "aiPlatformFloorSetting")
    static let floorSettingMetadata = CodingKeys(stringValue: "floorSettingMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "filterConfig",
      "enableFloorSettingEnforcement",
      "integratedServices",
      "aiPlatformFloorSetting",
      "floorSettingMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.filterConfig = try container.decodeIfPresent(FilterConfig.self, forKey: .filterConfig)
    self.enableFloorSettingEnforcement = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableFloorSettingEnforcement)
    if let value = try container.decodeIfPresent(
      [FloorSetting.IntegratedService].self, forKey: .integratedServices)
    {
      self.integratedServices = value
    }
    self.aiPlatformFloorSetting = try container.decodeIfPresent(
      AiPlatformFloorSetting.self, forKey: .aiPlatformFloorSetting)
    self.floorSettingMetadata = try container.decodeIfPresent(
      FloorSetting.FloorSettingMetadata.self, forKey: .floorSettingMetadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.filterConfig, forKey: .filterConfig)
    try container.encodeIfPresent(
      self.enableFloorSettingEnforcement, forKey: .enableFloorSettingEnforcement)
    try container.encode(self.integratedServices, forKey: .integratedServices)
    try container.encodeIfPresent(self.aiPlatformFloorSetting, forKey: .aiPlatformFloorSetting)
    try container.encodeIfPresent(self.floorSettingMetadata, forKey: .floorSettingMetadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// message describing FloorSetting Metadata
  public struct FloorSettingMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Metadata for multi language detection.
    public var multiLanguageDetection: FloorSetting.FloorSettingMetadata.MultiLanguageDetection? =
      nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FloorSettingMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FloorSettingMetadata().with { $0.multiLanguageDetection = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let multiLanguageDetection = CodingKeys(stringValue: "multiLanguageDetection")

      static let _knownKeys: Set<Swift.String> = [
        "multiLanguageDetection"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.multiLanguageDetection = try container.decodeIfPresent(
        FloorSetting.FloorSettingMetadata.MultiLanguageDetection.self,
        forKey: .multiLanguageDetection)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.multiLanguageDetection, forKey: .multiLanguageDetection)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Metadata to enable multi language detection via floor setting.
    public struct MultiLanguageDetection: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. If true, multi language detection will be enabled.
      public var enableMultiLanguageDetection: Swift.Bool = Swift.Bool()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `MultiLanguageDetection`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MultiLanguageDetection().with { $0.enableMultiLanguageDetection = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let enableMultiLanguageDetection = CodingKeys(
          stringValue: "enableMultiLanguageDetection")

        static let _knownKeys: Set<Swift.String> = [
          "enableMultiLanguageDetection"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          Swift.Bool.self, forKey: .enableMultiLanguageDetection)
        {
          self.enableMultiLanguageDetection = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(
          self.enableMultiLanguageDetection, forKey: .enableMultiLanguageDetection)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.modelarmor.v1.FloorSetting.FloorSettingMetadata.MultiLanguageDetection"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.FloorSetting.FloorSettingMetadata"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Integrated service for which the floor setting is applicable.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum IntegratedService: Codable, Equatable, Sendable {
    /// Unspecified integrated service.
    case unspecified
    /// AI Platform.
    case aiPlatform
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .aiPlatform: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INTEGRATED_SERVICE_UNSPECIFIED"
      case .aiPlatform: return "AI_PLATFORM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:IntegratedService/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INTEGRATED_SERVICE_UNSPECIFIED": self = .unspecified
      case "AI_PLATFORM": self = .aiPlatform
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:IntegratedService/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .aiPlatform
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("INTEGRATED_SERVICE_UNSPECIFIED")
      case .aiPlatform: return try container.encode("AI_PLATFORM")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.FloorSetting"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
