// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Malicious URI Filter Result.
public struct MaliciousUriFilterResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Reports whether Malicious URI filter was successfully executed
  /// or not.
  public var executionState: FilterExecutionState = FilterExecutionState()

  /// Optional messages corresponding to the result.
  /// A message can provide warnings or error details.
  /// For example, if execution state is skipped then this field provides
  /// related reason/explanation.
  public var messageItems: [MessageItem] = []

  /// Output only. Match state for this Malicious URI.
  /// Value is MATCH_FOUND if at least one Malicious URI is found.
  public var matchState: FilterMatchState = FilterMatchState()

  /// List of Malicious URIs found in data.
  public var maliciousUriMatchedItems: [MaliciousUriFilterResult.MaliciousUriMatchedItem] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MaliciousUriFilterResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaliciousUriFilterResult().with { $0.executionState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let executionState = CodingKeys(stringValue: "executionState")
    static let messageItems = CodingKeys(stringValue: "messageItems")
    static let matchState = CodingKeys(stringValue: "matchState")
    static let maliciousUriMatchedItems = CodingKeys(stringValue: "maliciousUriMatchedItems")

    static let _knownKeys: Set<Swift.String> = [
      "executionState",
      "messageItems",
      "matchState",
      "maliciousUriMatchedItems",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(FilterExecutionState.self, forKey: .executionState)
    {
      self.executionState = value
    }
    if let value = try container.decodeIfPresent([MessageItem].self, forKey: .messageItems) {
      self.messageItems = value
    }
    if let value = try container.decodeIfPresent(FilterMatchState.self, forKey: .matchState) {
      self.matchState = value
    }
    if let value = try container.decodeIfPresent(
      [MaliciousUriFilterResult.MaliciousUriMatchedItem].self, forKey: .maliciousUriMatchedItems)
    {
      self.maliciousUriMatchedItems = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.executionState, forKey: .executionState)
    try container.encode(self.messageItems, forKey: .messageItems)
    try container.encode(self.matchState, forKey: .matchState)
    try container.encode(self.maliciousUriMatchedItems, forKey: .maliciousUriMatchedItems)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Information regarding malicious URI and its location within the input
  /// content.
  public struct MaliciousUriMatchedItem: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Malicious URI.
    public var uri: Swift.String = Swift.String()

    /// List of locations where Malicious URI is identified.
    /// The `locations` field is supported only for plaintext content i.e.
    /// ByteItemType.PLAINTEXT_UTF8
    public var locations: [RangeInfo] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MaliciousUriMatchedItem`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MaliciousUriMatchedItem().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uri = CodingKeys(stringValue: "uri")
      static let locations = CodingKeys(stringValue: "locations")

      static let _knownKeys: Set<Swift.String> = [
        "uri",
        "locations",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
        self.uri = value
      }
      if let value = try container.decodeIfPresent([RangeInfo].self, forKey: .locations) {
        self.locations = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uri, forKey: .uri)
      try container.encode(self.locations, forKey: .locations)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.modelarmor.v1.MaliciousUriFilterResult.MaliciousUriMatchedItem"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.MaliciousUriFilterResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
