// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ModelArmorRetry: ModelArmorStub {
    let inner: any ModelArmorStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any ModelArmorStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listTemplates(
      request: ListTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.ListTemplatesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTemplatesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.ListTemplatesResponse
          in
          return try await self.inner.listTemplates(request: r, options: o)
        })
    }

    public func getTemplate(
      request: GetTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.Template
          in
          return try await self.inner.getTemplate(request: r, options: o)
        })
    }

    public func createTemplate(
      request: CreateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.Template
          in
          return try await self.inner.createTemplate(request: r, options: o)
        })
    }

    public func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.Template
          in
          return try await self.inner.updateTemplate(request: r, options: o)
        })
    }

    public func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteTemplateRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTemplate(request: r, options: o)
        })
    }

    public func getFloorSetting(
      request: GetFloorSettingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetFloorSettingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.FloorSetting
          in
          return try await self.inner.getFloorSetting(request: r, options: o)
        })
    }

    public func updateFloorSetting(
      request: UpdateFloorSettingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateFloorSettingRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.FloorSetting
          in
          return try await self.inner.updateFloorSetting(request: r, options: o)
        })
    }

    public func sanitizeUserPrompt(
      request: SanitizeUserPromptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SanitizeUserPromptRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse
          in
          return try await self.inner.sanitizeUserPrompt(request: r, options: o)
        })
    }

    public func sanitizeModelResponse(
      request: SanitizeModelResponseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SanitizeModelResponseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse
          in
          return try await self.inner.sanitizeModelResponse(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
