// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "ModelArmorQuickstart")
public final class ModelArmorClient: Clients.ModelArmorProtocol, Sendable {
  let inner: any Clients.ModelArmorStub

  /// Creates a new `ModelArmorClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ModelArmorStub = try Clients.ModelArmorTransport(options)
    inner = Clients.ModelArmorRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ModelArmorLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists Templates in a given project and location.
  ///
  /// @Snippet(path: "ModelArmor_ListTemplates")
  public func listTemplates(
    request: ListTemplatesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.ListTemplatesResponse {
    try await self.inner.listTemplates(request: request, options: options)
  }

  /// Gets details of a single Template.
  ///
  /// @Snippet(path: "ModelArmor_GetTemplate")
  public func getTemplate(
    request: GetTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.Template {
    try await self.inner.getTemplate(request: request, options: options)
  }

  /// Creates a new Template in a given project and location.
  ///
  /// @Snippet(path: "ModelArmor_CreateTemplate")
  public func createTemplate(
    request: CreateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.Template {
    try await self.inner.createTemplate(request: request, options: options)
  }

  /// Updates the parameters of a single Template.
  ///
  /// @Snippet(path: "ModelArmor_UpdateTemplate")
  public func updateTemplate(
    request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.Template {
    try await self.inner.updateTemplate(request: request, options: options)
  }

  /// Deletes a single Template.
  ///
  /// @Snippet(path: "ModelArmor_DeleteTemplate")
  public func deleteTemplate(
    request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTemplate(request: request, options: options)
  }

  /// Gets details of a single floor setting of a project
  ///
  /// @Snippet(path: "ModelArmor_GetFloorSetting")
  public func getFloorSetting(
    request: GetFloorSettingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
    try await self.inner.getFloorSetting(request: request, options: options)
  }

  /// Updates the parameters of a single floor setting of a project
  ///
  /// @Snippet(path: "ModelArmor_UpdateFloorSetting")
  public func updateFloorSetting(
    request: UpdateFloorSettingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
    try await self.inner.updateFloorSetting(request: request, options: options)
  }

  /// Sanitizes User Prompt.
  ///
  /// @Snippet(path: "ModelArmor_SanitizeUserPrompt")
  public func sanitizeUserPrompt(
    request: SanitizeUserPromptRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse {
    try await self.inner.sanitizeUserPrompt(request: request, options: options)
  }

  /// Sanitizes Model Response.
  ///
  /// @Snippet(path: "ModelArmor_SanitizeModelResponse")
  public func sanitizeModelResponse(
    request: SanitizeModelResponseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse {
    try await self.inner.sanitizeModelResponse(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ModelArmor_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ModelArmor_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ModelArmorClient`.
  ///
  /// To mock `ModelArmorClient` change your functions to receive
  /// `some ModelArmorProtocol` or `any ModelArmorProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ModelArmorProtocol: Sendable {
    /// See `ModelArmorClient.listTemplates`.
    func listTemplates(
      request: ListTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.ListTemplatesResponse

    /// See `ModelArmorClient.getTemplate`.
    func getTemplate(
      request: GetTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template

    /// See `ModelArmorClient.createTemplate`.
    func createTemplate(
      request: CreateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template

    /// See `ModelArmorClient.updateTemplate`.
    func updateTemplate(
      request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.Template

    /// See `ModelArmorClient.deleteTemplate`.
    func deleteTemplate(
      request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ModelArmorClient.getFloorSetting`.
    func getFloorSetting(
      request: GetFloorSettingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting

    /// See `ModelArmorClient.updateFloorSetting`.
    func updateFloorSetting(
      request: UpdateFloorSettingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.FloorSetting

    /// See `ModelArmorClient.sanitizeUserPrompt`.
    func sanitizeUserPrompt(
      request: SanitizeUserPromptRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse

    /// See `ModelArmorClient.sanitizeModelResponse`.
    func sanitizeModelResponse(
      request: SanitizeModelResponseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse

    /// See `ModelArmorClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ModelArmorClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.ModelArmorProtocol {
  public func listTemplates(request: ListTemplatesRequest) async throws
    -> GoogleCloudModelArmorV1.ListTemplatesResponse
  {
    try await self.listTemplates(request: request, options: .init())
  }

  public func listTemplates(
    request: ListTemplatesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.ListTemplatesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listTemplates(
    byItem: ListTemplatesRequest
  ) -> any AsyncSequence<Template, Swift.Error> {
    self.listTemplates(byItem: byItem, options: .init())
  }

  /// Lists Templates in a given project and location.
  ///
  /// @Snippet(path: "ModelArmor_ListTemplates")
  public func listTemplates(
    byItem: ListTemplatesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Template, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudModelArmorV1.ListTemplatesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTemplates(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTemplates(
    parent: Swift.String,
  ) -> any AsyncSequence<Template, Swift.Error> {
    let request = ListTemplatesRequest().with {
      $0.parent = parent
    }
    return self.listTemplates(byItem: request)
  }

  public func getTemplate(request: GetTemplateRequest) async throws
    -> GoogleCloudModelArmorV1.Template
  {
    try await self.getTemplate(request: request, options: .init())
  }

  public func getTemplate(
    request: GetTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.Template {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getTemplate(
    name: Swift.String,
  ) async throws -> GoogleCloudModelArmorV1.Template {
    let request = GetTemplateRequest().with {
      $0.name = name
    }
    return try await self.getTemplate(request: request)
  }

  public func createTemplate(request: CreateTemplateRequest) async throws
    -> GoogleCloudModelArmorV1.Template
  {
    try await self.createTemplate(request: request, options: .init())
  }

  public func createTemplate(
    request: CreateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.Template {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createTemplate(
    parent: Swift.String,
    template: Template?,
    templateId: Swift.String,
  ) async throws -> GoogleCloudModelArmorV1.Template {
    let request = CreateTemplateRequest().with {
      $0.parent = parent
      $0.template = template
      $0.templateId = templateId
    }
    return try await self.createTemplate(request: request)
  }

  public func updateTemplate(request: UpdateTemplateRequest) async throws
    -> GoogleCloudModelArmorV1.Template
  {
    try await self.updateTemplate(request: request, options: .init())
  }

  public func updateTemplate(
    request: UpdateTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.Template {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateTemplate(
    template: Template?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudModelArmorV1.Template {
    let request = UpdateTemplateRequest().with {
      $0.template = template
      $0.updateMask = updateMask
    }
    return try await self.updateTemplate(request: request)
  }

  public func deleteTemplate(request: DeleteTemplateRequest) async throws {
    try await self.deleteTemplate(request: request, options: .init())
  }

  public func deleteTemplate(
    request: DeleteTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteTemplate(
    name: Swift.String,
  ) async throws {
    let request = DeleteTemplateRequest().with {
      $0.name = name
    }
    try await self.deleteTemplate(request: request)
  }

  public func getFloorSetting(request: GetFloorSettingRequest) async throws
    -> GoogleCloudModelArmorV1.FloorSetting
  {
    try await self.getFloorSetting(request: request, options: .init())
  }

  public func getFloorSetting(
    request: GetFloorSettingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getFloorSetting(
    name: Swift.String,
  ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
    let request = GetFloorSettingRequest().with {
      $0.name = name
    }
    return try await self.getFloorSetting(request: request)
  }

  public func updateFloorSetting(request: UpdateFloorSettingRequest) async throws
    -> GoogleCloudModelArmorV1.FloorSetting
  {
    try await self.updateFloorSetting(request: request, options: .init())
  }

  public func updateFloorSetting(
    request: UpdateFloorSettingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateFloorSetting(
    floorSetting: FloorSetting?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudModelArmorV1.FloorSetting {
    let request = UpdateFloorSettingRequest().with {
      $0.floorSetting = floorSetting
      $0.updateMask = updateMask
    }
    return try await self.updateFloorSetting(request: request)
  }

  public func sanitizeUserPrompt(request: SanitizeUserPromptRequest) async throws
    -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse
  {
    try await self.sanitizeUserPrompt(request: request, options: .init())
  }

  public func sanitizeUserPrompt(
    request: SanitizeUserPromptRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.SanitizeUserPromptResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func sanitizeModelResponse(request: SanitizeModelResponseRequest) async throws
    -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse
  {
    try await self.sanitizeModelResponse(request: request, options: .init())
  }

  public func sanitizeModelResponse(
    request: SanitizeModelResponseRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudModelArmorV1.SanitizeModelResponseResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ModelArmor_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }
}
