// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message for Enabling Multi Language Detection.
public struct MultiLanguageDetectionMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Optional Source language of the user prompt.
  ///
  /// If multi-language detection is enabled but language is not set in that case
  /// we would automatically detect the source language.
  public var sourceLanguage: Swift.String = Swift.String()

  /// Optional. Enable detection of multi-language prompts and responses.
  public var enableMultiLanguageDetection: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MultiLanguageDetectionMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MultiLanguageDetectionMetadata().with { $0.sourceLanguage = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let sourceLanguage = CodingKeys(stringValue: "sourceLanguage")
    static let enableMultiLanguageDetection = CodingKeys(
      stringValue: "enableMultiLanguageDetection")

    static let _knownKeys: Set<Swift.String> = [
      "sourceLanguage",
      "enableMultiLanguageDetection",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceLanguage) {
      self.sourceLanguage = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableMultiLanguageDetection)
    {
      self.enableMultiLanguageDetection = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.sourceLanguage, forKey: .sourceLanguage)
    try container.encode(self.enableMultiLanguageDetection, forKey: .enableMultiLanguageDetection)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.MultiLanguageDetectionMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
