// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Responsible AI Result.
public struct RaiFilterResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Reports whether the RAI filter was successfully executed or
  /// not.
  public var executionState: FilterExecutionState = FilterExecutionState()

  /// Optional messages corresponding to the result.
  /// A message can provide warnings or error details.
  /// For example, if execution state is skipped then this field provides
  /// related reason/explanation.
  public var messageItems: [MessageItem] = []

  /// Output only. Overall filter match state for RAI.
  /// Value is MATCH_FOUND if at least one RAI filter confidence level is
  /// equal to or higher than the confidence level defined in configuration.
  public var matchState: FilterMatchState = FilterMatchState()

  /// The map of RAI filter results where key is RAI filter type - either of
  /// "sexually_explicit", "hate_speech", "harassment", "dangerous", "violence",
  /// "sexually_suggestive".
  public var raiFilterTypeResults: [Swift.String: RaiFilterResult.RaiFilterTypeResult] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RaiFilterResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RaiFilterResult().with { $0.executionState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let executionState = CodingKeys(stringValue: "executionState")
    static let messageItems = CodingKeys(stringValue: "messageItems")
    static let matchState = CodingKeys(stringValue: "matchState")
    static let raiFilterTypeResults = CodingKeys(stringValue: "raiFilterTypeResults")

    static let _knownKeys: Set<Swift.String> = [
      "executionState",
      "messageItems",
      "matchState",
      "raiFilterTypeResults",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(FilterExecutionState.self, forKey: .executionState)
    {
      self.executionState = value
    }
    if let value = try container.decodeIfPresent([MessageItem].self, forKey: .messageItems) {
      self.messageItems = value
    }
    if let value = try container.decodeIfPresent(FilterMatchState.self, forKey: .matchState) {
      self.matchState = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: RaiFilterResult.RaiFilterTypeResult].self, forKey: .raiFilterTypeResults)
    {
      self.raiFilterTypeResults = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.executionState, forKey: .executionState)
    try container.encode(self.messageItems, forKey: .messageItems)
    try container.encode(self.matchState, forKey: .matchState)
    try container.encode(self.raiFilterTypeResults, forKey: .raiFilterTypeResults)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Detailed Filter result for each of the responsible AI Filter Types.
  public struct RaiFilterTypeResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Type of responsible AI filter.
    public var filterType: RaiFilterType = RaiFilterType()

    /// Confidence level identified for this RAI filter.
    public var confidenceLevel: DetectionConfidenceLevel = DetectionConfidenceLevel()

    /// Output only. Match state for this RAI filter.
    public var matchState: FilterMatchState = FilterMatchState()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RaiFilterTypeResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RaiFilterTypeResult().with { $0.filterType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let filterType = CodingKeys(stringValue: "filterType")
      static let confidenceLevel = CodingKeys(stringValue: "confidenceLevel")
      static let matchState = CodingKeys(stringValue: "matchState")

      static let _knownKeys: Set<Swift.String> = [
        "filterType",
        "confidenceLevel",
        "matchState",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(RaiFilterType.self, forKey: .filterType) {
        self.filterType = value
      }
      if let value = try container.decodeIfPresent(
        DetectionConfidenceLevel.self, forKey: .confidenceLevel)
      {
        self.confidenceLevel = value
      }
      if let value = try container.decodeIfPresent(FilterMatchState.self, forKey: .matchState) {
        self.matchState = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.filterType, forKey: .filterType)
      try container.encode(self.confidenceLevel, forKey: .confidenceLevel)
      try container.encode(self.matchState, forKey: .matchState)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.RaiFilterResult.RaiFilterTypeResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.RaiFilterResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
