// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Sanitization result after applying all the filters on input content.
public struct SanitizationResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Overall filter match state for Sanitization.
  /// The state can have below two values.
  ///
  /// 1) NO_MATCH_FOUND: No filters in configuration satisfy matching criteria.
  /// In other words, input passed all filters.
  ///
  /// 2) MATCH_FOUND: At least one filter in configuration satisfies matching.
  /// In other words, input did not pass one or more filters.
  public var filterMatchState: FilterMatchState = FilterMatchState()

  /// Output only. Results for all filters where the key is the filter name -
  /// either of "csam", "malicious_uris", "rai", "pi_and_jailbreak" ,"sdp".
  public var filterResults: [Swift.String: FilterResult] = [:]

  /// Output only. A field indicating the outcome of the invocation, irrespective
  /// of match status. It can have the following three values: SUCCESS: All
  /// filters were executed successfully. PARTIAL: Some filters were skipped or
  /// failed execution. FAILURE: All filters were skipped or failed execution.
  public var invocationResult: InvocationResult = InvocationResult()

  /// Output only. Metadata related to Sanitization.
  public var sanitizationMetadata: SanitizationResult.SanitizationMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SanitizationResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SanitizationResult().with { $0.filterMatchState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let filterMatchState = CodingKeys(stringValue: "filterMatchState")
    static let filterResults = CodingKeys(stringValue: "filterResults")
    static let invocationResult = CodingKeys(stringValue: "invocationResult")
    static let sanitizationMetadata = CodingKeys(stringValue: "sanitizationMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "filterMatchState",
      "filterResults",
      "invocationResult",
      "sanitizationMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(FilterMatchState.self, forKey: .filterMatchState) {
      self.filterMatchState = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: FilterResult].self, forKey: .filterResults)
    {
      self.filterResults = value
    }
    if let value = try container.decodeIfPresent(InvocationResult.self, forKey: .invocationResult) {
      self.invocationResult = value
    }
    self.sanitizationMetadata = try container.decodeIfPresent(
      SanitizationResult.SanitizationMetadata.self, forKey: .sanitizationMetadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.filterMatchState, forKey: .filterMatchState)
    try container.encode(self.filterResults, forKey: .filterResults)
    try container.encode(self.invocationResult, forKey: .invocationResult)
    try container.encodeIfPresent(self.sanitizationMetadata, forKey: .sanitizationMetadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Message describing Sanitization metadata.
  public struct SanitizationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Error code if any.
    public var errorCode: Swift.Int64 = Swift.Int64()

    /// Error message if any.
    public var errorMessage: Swift.String = Swift.String()

    /// Passthrough field defined in TemplateMetadata to indicate whether to
    /// ignore partial invocation failures.
    public var ignorePartialInvocationFailures: Swift.Bool = Swift.Bool()

    /// Output only. The stream chunk processed by the Sanitization service.
    public var streamChunkProcessed: DataItem? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SanitizationMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SanitizationMetadata().with { $0.errorCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let errorCode = CodingKeys(stringValue: "errorCode")
      static let errorMessage = CodingKeys(stringValue: "errorMessage")
      static let ignorePartialInvocationFailures = CodingKeys(
        stringValue: "ignorePartialInvocationFailures")
      static let streamChunkProcessed = CodingKeys(stringValue: "streamChunkProcessed")

      static let _knownKeys: Set<Swift.String> = [
        "errorCode",
        "errorMessage",
        "ignorePartialInvocationFailures",
        "streamChunkProcessed",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .errorCode) {
        self.errorCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage) {
        self.errorMessage = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .ignorePartialInvocationFailures)
      {
        self.ignorePartialInvocationFailures = value
      }
      self.streamChunkProcessed = try container.decodeIfPresent(
        DataItem.self, forKey: .streamChunkProcessed)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.errorCode, forKey: .errorCode)
      try container.encode(self.errorMessage, forKey: .errorMessage)
      try container.encode(
        self.ignorePartialInvocationFailures, forKey: .ignorePartialInvocationFailures)
      try container.encodeIfPresent(self.streamChunkProcessed, forKey: .streamChunkProcessed)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.modelarmor.v1.SanitizationResult.SanitizationMetadata"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SanitizationResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
