// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Sanitize Model Response request.
public struct SanitizeModelResponseRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Represents resource name of template
  /// e.g. name=projects/sample-project/locations/us-central1/templates/templ01
  public var name: Swift.String = Swift.String()

  /// Required. Model response data to sanitize.
  public var modelResponseData: DataItem? = nil

  /// Optional. User Prompt associated with Model response.
  public var userPrompt: Swift.String = Swift.String()

  /// Optional. Metadata related for multi language detection.
  public var multiLanguageDetectionMetadata: MultiLanguageDetectionMetadata? = nil

  /// Optional. Streaming Mode for StreamSanitize* API.
  public var streamingMode: StreamingMode? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SanitizeModelResponseRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SanitizeModelResponseRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let modelResponseData = CodingKeys(stringValue: "modelResponseData")
    static let userPrompt = CodingKeys(stringValue: "userPrompt")
    static let multiLanguageDetectionMetadata = CodingKeys(
      stringValue: "multiLanguageDetectionMetadata")
    static let streamingMode = CodingKeys(stringValue: "streamingMode")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "modelResponseData",
      "userPrompt",
      "multiLanguageDetectionMetadata",
      "streamingMode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.modelResponseData = try container.decodeIfPresent(
      DataItem.self, forKey: .modelResponseData)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userPrompt) {
      self.userPrompt = value
    }
    self.multiLanguageDetectionMetadata = try container.decodeIfPresent(
      MultiLanguageDetectionMetadata.self, forKey: .multiLanguageDetectionMetadata)
    self.streamingMode = try container.decodeIfPresent(StreamingMode.self, forKey: .streamingMode)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.modelResponseData, forKey: .modelResponseData)
    try container.encode(self.userPrompt, forKey: .userPrompt)
    try container.encodeIfPresent(
      self.multiLanguageDetectionMetadata, forKey: .multiLanguageDetectionMetadata)
    try container.encodeIfPresent(self.streamingMode, forKey: .streamingMode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SanitizeModelResponseRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
