// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Sensitive Data Protection Advanced configuration.
public struct SdpAdvancedConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Sensitive Data Protection inspect template resource name
  ///
  /// If only inspect template is provided (de-identify template not provided),
  /// then Sensitive Data Protection InspectContent action is performed during
  /// Sanitization. All Sensitive Data Protection findings identified during
  /// inspection will be returned as SdpFinding in SdpInsepctionResult.
  ///
  /// e.g.
  /// `projects/{project}/locations/{location}/inspectTemplates/{inspect_template}`
  public var inspectTemplate: Swift.String = Swift.String()

  /// Optional. Optional Sensitive Data Protection Deidentify template resource
  /// name.
  ///
  /// If provided then DeidentifyContent action is performed during Sanitization
  /// using this template and inspect template. The De-identified data will
  /// be returned in SdpDeidentifyResult.
  /// Note that all info-types present in the deidentify template must be present
  /// in inspect template.
  ///
  /// e.g.
  /// `projects/{project}/locations/{location}/deidentifyTemplates/{deidentify_template}`
  public var deidentifyTemplate: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SdpAdvancedConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpAdvancedConfig().with { $0.inspectTemplate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inspectTemplate = CodingKeys(stringValue: "inspectTemplate")
    static let deidentifyTemplate = CodingKeys(stringValue: "deidentifyTemplate")

    static let _knownKeys: Set<Swift.String> = [
      "inspectTemplate",
      "deidentifyTemplate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inspectTemplate) {
      self.inspectTemplate = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deidentifyTemplate) {
      self.deidentifyTemplate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inspectTemplate, forKey: .inspectTemplate)
    try container.encode(self.deidentifyTemplate, forKey: .deidentifyTemplate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpAdvancedConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
