// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Sensitive Data Protection Deidentification Result.
public struct SdpDeidentifyResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Reports whether Sensitive Data Protection deidentification was
  /// successfully executed or not.
  public var executionState: FilterExecutionState = FilterExecutionState()

  /// Optional messages corresponding to the result.
  /// A message can provide warnings or error details.
  /// For example, if execution state is skipped then this field provides
  /// related reason/explanation.
  public var messageItems: [MessageItem] = []

  /// Output only. Match state for Sensitive Data Protection Deidentification.
  /// Value is MATCH_FOUND if content is de-identified.
  public var matchState: FilterMatchState = FilterMatchState()

  /// De-identified data.
  public var data: DataItem? = nil

  /// Total size in bytes that were transformed during deidentification.
  public var transformedBytes: Swift.Int64 = Swift.Int64()

  /// List of Sensitive Data Protection info-types that were de-identified.
  public var infoTypes: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SdpDeidentifyResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpDeidentifyResult().with { $0.executionState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let executionState = CodingKeys(stringValue: "executionState")
    static let messageItems = CodingKeys(stringValue: "messageItems")
    static let matchState = CodingKeys(stringValue: "matchState")
    static let data = CodingKeys(stringValue: "data")
    static let transformedBytes = CodingKeys(stringValue: "transformedBytes")
    static let infoTypes = CodingKeys(stringValue: "infoTypes")

    static let _knownKeys: Set<Swift.String> = [
      "executionState",
      "messageItems",
      "matchState",
      "data",
      "transformedBytes",
      "infoTypes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(FilterExecutionState.self, forKey: .executionState)
    {
      self.executionState = value
    }
    if let value = try container.decodeIfPresent([MessageItem].self, forKey: .messageItems) {
      self.messageItems = value
    }
    if let value = try container.decodeIfPresent(FilterMatchState.self, forKey: .matchState) {
      self.matchState = value
    }
    self.data = try container.decodeIfPresent(DataItem.self, forKey: .data)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .transformedBytes) {
      self.transformedBytes = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .infoTypes) {
      self.infoTypes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.executionState, forKey: .executionState)
    try container.encode(self.messageItems, forKey: .messageItems)
    try container.encode(self.matchState, forKey: .matchState)
    try container.encodeIfPresent(self.data, forKey: .data)
    try container.encode(self.transformedBytes, forKey: .transformedBytes)
    try container.encode(self.infoTypes, forKey: .infoTypes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpDeidentifyResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
