// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Sensitive Data Protection filter result.
public struct SdpFilterResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Either of Sensitive Data Protection Inspect result or Deidentify result.
  public var result: OneOf_Result? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SdpFilterResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpFilterResult().with { $0.inspectResult = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inspectResult = CodingKeys(stringValue: "inspectResult")
    static let deidentifyResult = CodingKeys(stringValue: "deidentifyResult")
    static let redactResult = CodingKeys(stringValue: "redactResult")

    static let _knownKeys: Set<Swift.String> = [
      "inspectResult",
      "deidentifyResult",
      "redactResult",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var result: OneOf_Result? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let inspectResult = try container.decodeIfPresent(
      SdpInspectResult?.self, forKey: .inspectResult)
    {
      try resultCheckAndSet(.inspectResult(inspectResult))
    }
    if let deidentifyResult = try container.decodeIfPresent(
      SdpDeidentifyResult?.self, forKey: .deidentifyResult)
    {
      try resultCheckAndSet(.deidentifyResult(deidentifyResult))
    }
    if let redactResult = try container.decodeIfPresent(
      SdpRedactResult?.self, forKey: .redactResult)
    {
      try resultCheckAndSet(.redactResult(redactResult))
    }
    self.result = result
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.result {
      switch choice {
      case .inspectResult(let value):
        try container.encode(value, forKey: .inspectResult)
      case .deidentifyResult(let value):
        try container.encode(value, forKey: .deidentifyResult)
      case .redactResult(let value):
        try container.encode(value, forKey: .redactResult)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Either of Sensitive Data Protection Inspect result or Deidentify result.
  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// Sensitive Data Protection Inspection result if inspection is performed.
    indirect case inspectResult(SdpInspectResult?)
    /// Sensitive Data Protection Deidentification result if deidentification is
    /// performed.
    indirect case deidentifyResult(SdpDeidentifyResult?)
    /// Sensitive Data Protection Redaction result if redaction is performed.
    /// This is primarily used for image redaction.
    indirect case redactResult(SdpRedactResult?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpFilterResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
