// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Finding corresponding to Sensitive Data Protection filter.
public struct SdpFinding: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of Sensitive Data Protection info type for this finding.
  public var infoType: Swift.String = Swift.String()

  /// Identified confidence likelihood for `info_type`.
  public var likelihood: SdpFindingLikelihood = SdpFindingLikelihood()

  /// Location for this finding.
  public var location: SdpFinding.SdpFindingLocation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SdpFinding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpFinding().with { $0.infoType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let infoType = CodingKeys(stringValue: "infoType")
    static let likelihood = CodingKeys(stringValue: "likelihood")
    static let location = CodingKeys(stringValue: "location")

    static let _knownKeys: Set<Swift.String> = [
      "infoType",
      "likelihood",
      "location",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .infoType) {
      self.infoType = value
    }
    if let value = try container.decodeIfPresent(SdpFindingLikelihood.self, forKey: .likelihood) {
      self.likelihood = value
    }
    self.location = try container.decodeIfPresent(
      SdpFinding.SdpFindingLocation.self, forKey: .location)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.infoType, forKey: .infoType)
    try container.encode(self.likelihood, forKey: .likelihood)
    try container.encodeIfPresent(self.location, forKey: .location)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Location of this Sensitive Data Protection Finding within input content.
  public struct SdpFindingLocation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Zero-based byte offsets delimiting the finding.
    /// These are relative to the finding's containing element.
    /// Note that when the content is not textual, this references
    /// the UTF-8 encoded textual representation of the content.
    /// Note: Omitted if content is an image.
    public var byteRange: RangeInfo? = nil

    /// Unicode character offsets delimiting the finding.
    /// These are relative to the finding's containing element.
    /// Provided when the content is text.
    /// Note: Omitted if content is an image.
    public var codepointRange: RangeInfo? = nil

    /// List of nested objects pointing to the precise location of the finding
    /// within an image, file or record.
    ///
    /// For example, a single finding might be detected in two
    /// separate bounding boxes within an image (e.g., if it wraps across
    /// a line or is partially obscured). In such cases, content_locations
    /// would contain two SdpContentLocation entries, each with an
    /// image_finding_location pointing to a different bounding box.
    public var contentLocations: [SdpContentLocation] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SdpFindingLocation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SdpFindingLocation().with { $0.byteRange = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let byteRange = CodingKeys(stringValue: "byteRange")
      static let codepointRange = CodingKeys(stringValue: "codepointRange")
      static let contentLocations = CodingKeys(stringValue: "contentLocations")

      static let _knownKeys: Set<Swift.String> = [
        "byteRange",
        "codepointRange",
        "contentLocations",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.byteRange = try container.decodeIfPresent(RangeInfo.self, forKey: .byteRange)
      self.codepointRange = try container.decodeIfPresent(RangeInfo.self, forKey: .codepointRange)
      if let value = try container.decodeIfPresent(
        [SdpContentLocation].self, forKey: .contentLocations)
      {
        self.contentLocations = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.byteRange, forKey: .byteRange)
      try container.encodeIfPresent(self.codepointRange, forKey: .codepointRange)
      try container.encode(self.contentLocations, forKey: .contentLocations)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.SdpFinding.SdpFindingLocation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpFinding"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
