// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Location of the finding within an image.
public struct SdpImageFindingLocation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Bounding boxes locating the pixels within the image containing the finding.
  public var boundingBoxes: [SdpImageFindingLocation.SdpBoundingBox] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SdpImageFindingLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SdpImageFindingLocation().with { $0.boundingBoxes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let boundingBoxes = CodingKeys(stringValue: "boundingBoxes")

    static let _knownKeys: Set<Swift.String> = [
      "boundingBoxes"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [SdpImageFindingLocation.SdpBoundingBox].self, forKey: .boundingBoxes)
    {
      self.boundingBoxes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.boundingBoxes, forKey: .boundingBoxes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Bounding box encompassing a finding within an image.
  public struct SdpBoundingBox: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Top coordinate of the bounding box. (0,0) is upper left.
    public var top: Swift.Int32 = Swift.Int32()

    /// Left coordinate of the bounding box. (0,0) is upper left.
    public var `left`: Swift.Int32 = Swift.Int32()

    /// Width of the bounding box in pixels.
    public var width: Swift.Int32 = Swift.Int32()

    /// Height of the bounding box in pixels.
    public var height: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SdpBoundingBox`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SdpBoundingBox().with { $0.top = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let top = CodingKeys(stringValue: "top")
      static let `left` = CodingKeys(stringValue: "left")
      static let width = CodingKeys(stringValue: "width")
      static let height = CodingKeys(stringValue: "height")

      static let _knownKeys: Set<Swift.String> = [
        "top",
        "left",
        "width",
        "height",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .top) {
        self.top = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .`left`) {
        self.`left` = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .width) {
        self.width = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .height) {
        self.height = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.top, forKey: .top)
      try container.encode(self.`left`, forKey: .`left`)
      try container.encode(self.width, forKey: .width)
      try container.encode(self.height, forKey: .height)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.SdpImageFindingLocation.SdpBoundingBox"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.SdpImageFindingLocation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
