// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing Template resource
public struct Template: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. name of resource
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. filter configuration for this template
  public var filterConfig: FilterConfig? = nil

  /// Optional. metadata for this template
  public var templateMetadata: Template.TemplateMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Template`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Template().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let filterConfig = CodingKeys(stringValue: "filterConfig")
    static let templateMetadata = CodingKeys(stringValue: "templateMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "filterConfig",
      "templateMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.filterConfig = try container.decodeIfPresent(FilterConfig.self, forKey: .filterConfig)
    self.templateMetadata = try container.decodeIfPresent(
      Template.TemplateMetadata.self, forKey: .templateMetadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.filterConfig, forKey: .filterConfig)
    try container.encodeIfPresent(self.templateMetadata, forKey: .templateMetadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Message describing TemplateMetadata
  public struct TemplateMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. If true, partial detector failures should be ignored.
    public var ignorePartialInvocationFailures: Swift.Bool = Swift.Bool()

    /// Optional. Indicates the custom error code set by the user to be returned
    /// to the end user by the service extension if the prompt trips Model Armor
    /// filters.
    public var customPromptSafetyErrorCode: Swift.Int32 = Swift.Int32()

    /// Optional. Indicates the custom error message set by the user to be
    /// returned to the end user if the prompt trips Model Armor filters.
    public var customPromptSafetyErrorMessage: Swift.String = Swift.String()

    /// Optional. Indicates the custom error code set by the user to be returned
    /// to the end user if the LLM response trips Model Armor filters.
    public var customLlmResponseSafetyErrorCode: Swift.Int32 = Swift.Int32()

    /// Optional. Indicates the custom error message set by the user to be
    /// returned to the end user if the LLM response trips Model Armor filters.
    public var customLlmResponseSafetyErrorMessage: Swift.String = Swift.String()

    /// Optional. If true, log template crud operations.
    public var logTemplateOperations: Swift.Bool = Swift.Bool()

    /// Optional. If true, log sanitize operations.
    public var logSanitizeOperations: Swift.Bool = Swift.Bool()

    /// Optional. Enforcement type for Model Armor filters.
    public var enforcementType: Template.TemplateMetadata.EnforcementType = Template
      .TemplateMetadata.EnforcementType()

    /// Optional. Metadata for multi language detection.
    public var multiLanguageDetection: Template.TemplateMetadata.MultiLanguageDetection? = nil

    /// Optional. Specifies the modalities to scan.
    /// If empty, only text modality will be scanned.
    public var modalities: [Modality] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TemplateMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TemplateMetadata().with { $0.ignorePartialInvocationFailures = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ignorePartialInvocationFailures = CodingKeys(
        stringValue: "ignorePartialInvocationFailures")
      static let customPromptSafetyErrorCode = CodingKeys(
        stringValue: "customPromptSafetyErrorCode")
      static let customPromptSafetyErrorMessage = CodingKeys(
        stringValue: "customPromptSafetyErrorMessage")
      static let customLlmResponseSafetyErrorCode = CodingKeys(
        stringValue: "customLlmResponseSafetyErrorCode")
      static let customLlmResponseSafetyErrorMessage = CodingKeys(
        stringValue: "customLlmResponseSafetyErrorMessage")
      static let logTemplateOperations = CodingKeys(stringValue: "logTemplateOperations")
      static let logSanitizeOperations = CodingKeys(stringValue: "logSanitizeOperations")
      static let enforcementType = CodingKeys(stringValue: "enforcementType")
      static let multiLanguageDetection = CodingKeys(stringValue: "multiLanguageDetection")
      static let modalities = CodingKeys(stringValue: "modalities")

      static let _knownKeys: Set<Swift.String> = [
        "ignorePartialInvocationFailures",
        "customPromptSafetyErrorCode",
        "customPromptSafetyErrorMessage",
        "customLlmResponseSafetyErrorCode",
        "customLlmResponseSafetyErrorMessage",
        "logTemplateOperations",
        "logSanitizeOperations",
        "enforcementType",
        "multiLanguageDetection",
        "modalities",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .ignorePartialInvocationFailures)
      {
        self.ignorePartialInvocationFailures = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .customPromptSafetyErrorCode)
      {
        self.customPromptSafetyErrorCode = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .customPromptSafetyErrorMessage)
      {
        self.customPromptSafetyErrorMessage = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .customLlmResponseSafetyErrorCode)
      {
        self.customLlmResponseSafetyErrorCode = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .customLlmResponseSafetyErrorMessage)
      {
        self.customLlmResponseSafetyErrorMessage = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .logTemplateOperations)
      {
        self.logTemplateOperations = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .logSanitizeOperations)
      {
        self.logSanitizeOperations = value
      }
      if let value = try container.decodeIfPresent(
        Template.TemplateMetadata.EnforcementType.self, forKey: .enforcementType)
      {
        self.enforcementType = value
      }
      self.multiLanguageDetection = try container.decodeIfPresent(
        Template.TemplateMetadata.MultiLanguageDetection.self, forKey: .multiLanguageDetection)
      if let value = try container.decodeIfPresent([Modality].self, forKey: .modalities) {
        self.modalities = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(
        self.ignorePartialInvocationFailures, forKey: .ignorePartialInvocationFailures)
      try container.encode(self.customPromptSafetyErrorCode, forKey: .customPromptSafetyErrorCode)
      try container.encode(
        self.customPromptSafetyErrorMessage, forKey: .customPromptSafetyErrorMessage)
      try container.encode(
        self.customLlmResponseSafetyErrorCode, forKey: .customLlmResponseSafetyErrorCode)
      try container.encode(
        self.customLlmResponseSafetyErrorMessage, forKey: .customLlmResponseSafetyErrorMessage)
      try container.encode(self.logTemplateOperations, forKey: .logTemplateOperations)
      try container.encode(self.logSanitizeOperations, forKey: .logSanitizeOperations)
      try container.encode(self.enforcementType, forKey: .enforcementType)
      try container.encodeIfPresent(self.multiLanguageDetection, forKey: .multiLanguageDetection)
      try container.encode(self.modalities, forKey: .modalities)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Metadata to enable multi language detection via template.
    public struct MultiLanguageDetection: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. If true, multi language detection will be enabled.
      public var enableMultiLanguageDetection: Swift.Bool = Swift.Bool()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `MultiLanguageDetection`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MultiLanguageDetection().with { $0.enableMultiLanguageDetection = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let enableMultiLanguageDetection = CodingKeys(
          stringValue: "enableMultiLanguageDetection")

        static let _knownKeys: Set<Swift.String> = [
          "enableMultiLanguageDetection"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          Swift.Bool.self, forKey: .enableMultiLanguageDetection)
        {
          self.enableMultiLanguageDetection = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(
          self.enableMultiLanguageDetection, forKey: .enableMultiLanguageDetection)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.modelarmor.v1.Template.TemplateMetadata.MultiLanguageDetection"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Enforcement type for Model Armor filters.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum EnforcementType: Codable, Equatable, Hashable, Sendable {
      /// Default value. Same as INSPECT_AND_BLOCK.
      case unspecified
      /// Model Armor filters will run in inspect only mode. No action will be
      /// taken on the request.
      case inspectOnly
      /// Model Armor filters will run in inspect and block mode. Requests
      /// that trip Model Armor filters will be blocked.
      case inspectAndBlock
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .inspectOnly: return 1
        case .inspectAndBlock: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ENFORCEMENT_TYPE_UNSPECIFIED"
        case .inspectOnly: return "INSPECT_ONLY"
        case .inspectAndBlock: return "INSPECT_AND_BLOCK"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EnforcementType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ENFORCEMENT_TYPE_UNSPECIFIED": self = .unspecified
        case "INSPECT_ONLY": self = .inspectOnly
        case "INSPECT_AND_BLOCK": self = .inspectAndBlock
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EnforcementType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .inspectOnly
        case 2: self = .inspectAndBlock
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("ENFORCEMENT_TYPE_UNSPECIFIED")
        case .inspectOnly: return try container.encode("INSPECT_ONLY")
        case .inspectAndBlock: return try container.encode("INSPECT_AND_BLOCK")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.modelarmor.v1.Template.TemplateMetadata"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.modelarmor.v1.Template"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
